Algoritmo "CalcularPreço"

//[Vamos Calcular o preço da pintura ]
//Nome: Anthony Fuzinato
Var
// [Dados de Entrada]
   Comprimento: real
   Largura: real
// [Dados de Saida]
   Alateral: real
   Afrontal: real
   Ateto: real
   Atotal
INICIO
// [input]
   leia (Comprimento)
   leia (Largura)
// [processamento]
   ALateral <- (Comprimento * Largura)
   AreaPintar <- (AreaTotal * 0,015)
// [output]
   escreva (AreaPintar)
Fimalgoritmo




